app/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('cart/', views.cart, name="cart"),
    path('about/', views.about, name="about"),
    path('checkout/', views.checkout, name="checkout"),
    path('contact', views.contact, name="contact"),
    path('login/', views.loginUser, name="login"),
    path("logout/", views.Logout, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('store/', views.store, name="store"),
	path('add-to-cart/<slug>/',views.add_to_cart, name='add'),
    path('remove-from-cart-page/<slug>/',views.remove_from_cart_page, name='remove-from-cart-page'),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('item-detail/<str:pk>/', views.item_detail, name='item-detail'),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('add-to-wishlist/<slug>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('payment-completed/', views.payment_completed, name='payment-completed'),
    path('paypal-payment/', views.payment, name="paypal-payment"),
    path('payment-successful/', views.payment_successful, name="payment-successful"),
    path('paypal-failed/', views.payment_unsuccessful, name="payment-failed"),
    path("delete-review/<str:id>/", views.delete_review, name="delete-review"),
    path('remove-from-cart-page/<slug>/',views.remove_from_cart_page, name='remove-from-cart-page'),
    path('remove-item-from-cart-page/<slug>/',views.remove_single_item_from_cart_page, name='remove-single-item-from-cart-page'),
    path('add-item-to-cart-page/<slug>/',views.add_single_item_from_cart_page, name='add-single-item-to-cart-page'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('item-detail-add-to-cart/<slug>/',views.add_to_cart_item_detail_page, name='add-item-detail'),
	path('item-detail-remove-from-cart/<slug>/',views.remove_from_cart_item_detail_page, name='remove-item-detail'),
    path('order-detail/<str:pk>/', views.orderDetail, name='order-detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="app/password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password/password_reset_complete.html'), name='password_reset_complete'),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from unicodedata import lookup
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime,timedelta
from django.shortcuts import reverse
from multiselectfield import MultiSelectField
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.core.validators import RegexValidator
from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg
from django.utils import timezone

User = get_user_model()

class Brand(models.Model):
	name = models.CharField(max_length=100)
	class Meta:
		verbose_name_plural = "Brands"
	
	def __str__(self):
		return self.name
	
	class Meta:
		db_table = 'Brand'

class ItemColor(models.Model):
	color = models.CharField(max_length=100)
	class Meta:
		db_table = "ItemColor"
		verbose_name_plural = "Item Color"

	
	def __str__(self):
		return self.color


class Size(models.Model):
	size = models.CharField(max_length=5)
	class Meta:
		db_table = "Size"
		verbose_name_plural = "Size"
	
	def __str__(self):
		return self.size

class Category(models.Model):
	name = models.CharField(max_length=100)

	class Meta:
		db_table  = "Category"
		verbose_name_plural = 'Categories'
	
	def __str__(self):
		return self.name
	
class Item(models.Model):
	name = models.CharField(max_length=100)
	price = models.DecimalField(max_digits=7, decimal_places=2)
	discount_price = models.DecimalField(max_digits=7, decimal_places=2,blank=True, null=True)
	description = models.TextField(null=True, blank=True)
	category = models.ManyToManyField(Category)
	size = models.ForeignKey(Size, blank=True, null=True, on_delete=models.CASCADE)
	color = models.ManyToManyField(ItemColor)
	brand = models.ForeignKey(Brand, blank=True, null=True, on_delete=models.CASCADE)
	out_of_stock = models.BooleanField(default=False)
	slug = models.SlugField()

	def __str__(self):
		return self.name

	def get_average_rating(self):
		average_rating = Review.objects.filter(item=self).aggregate(Avg('rating'))['rating__avg']
		return average_rating

	def get_absolute_url(self):
		return reverse('store',kwargs={
		'slug':self.slug
		})

	def get_add_to_cart_url(self):
			return reverse('add',kwargs={
			'slug':self.slug
			})
	def get_add_to_wishlist_url(self):
			return reverse('add-to-wishlist',kwargs={
			'slug':self.slug
			})

	def get_remove_from_cart_url(self):
		return reverse('remove',kwargs={
			'slug':self.slug
			})
	
	def get_review_count(self):
		review_count = Review.objects.filter(item=self).count()
		return review_count

	class Meta:
		db_table  = "Item"

class OrderItem(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	ordered = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.quantity}x  {self.item.name}"

	def get_total_item_price(self):
		return self.quantity * self.item.price

	def get_total_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_total_discount_item_price()

	def get_final_price(self):
		if self.item.discount_price:
			return self.get_total_discount_item_price()
		else:
			return self.get_total_item_price()
		
	class Meta:
		db_table  = "OrderItem"


class Order(models.Model):
	STATUS_CHOICES = (
		('processing','Processing'),
		('on delivery', 'On delivery'),
		('delivered', 'Delivered'),
		('refund requested', 'Refund requested'),
		('refund declined','Refund declined'),
		('refund granted', 'Refund granted'),
		('refund completed', 'Refund completed'),
		('cancelled', 'Cancelled'),

	)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	ref_code = models.CharField(max_length=20,blank=True, null=True)
	items = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	status = models.CharField(max_length=100, choices=STATUS_CHOICES, blank=True, null=True)
	order_notes = models.CharField(max_length=200, blank=True, null=True)
	full_name = models.CharField(max_length=200)
	city = models.CharField(max_length=100)
	house_address = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	postal_code = models.CharField(max_length=100)
	phone = models.CharField(max_length=20)
	
	def __str__(self):
		return str(self.id)

	def get_total(self):
		total = 0
		for order_item in self.items.all():
			total += order_item.get_final_price()
		return total

	def set_order_status(self, val):
		status_dict = {x[1]:x[0] for x in self.STATUS_CHOICES}
		self.status = status_dict[val]

	class Meta:
		db_table  = "Order"


class Contact(models.Model):
	full_name = models.CharField(max_length=100)
	email = models.EmailField()
	message = models.TextField()
	read = models.BooleanField(default=False)
	def __str__(self):
		return self.email

	class Meta:
		db_table  = "Contact"
	

class Address(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	full_name = models.CharField(max_length=200)
	city = models.CharField(max_length=100)
	house_address = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	postal_code = models.CharField(max_length=100)
	phone = models.CharField(max_length=20)
	default = models.BooleanField(default=False)

	class Meta:
		db_table = "Address"
		verbose_name_plural = 'Addresses'

	def __str__(self):
		return (self.house_address)
	

class Review(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	comment = models.TextField(max_length=500)
	rating = models.IntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(5)])
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.item.name

	class Meta:
		db_table  = "Review"
	

class Wishlist(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	items = models.ManyToManyField(Item)
	
	def __str__(self):
		return str(self.id)
	
	class Meta:
		db_table  = "Wishlist"
	

class ItemImage(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	image = models.ImageField(null=True, blank=True)

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url
	
	def __str__(self):
		return self.item.name

	class Meta:
		db_table  = "ItemImage"

app/templates/app/dash/all-orders.html
{% extends 'app/base.html' %}
{% load static %}
{% load cart_template_tags %}

{% block content %}
{% include 'app/dash/dash-head-include.html' %}
  <!-- ======= Header ======= -->
  <!--  -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'dashboard' %}" class="logo d-flex align-items-center">

        <span class="d-none d-lg-block">Aurora</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->


        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="{% static 'assets/img/default-pic.png' %}" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.user.username}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'profile' %}">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>


          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header>
  <!-- End Header -->

{% include "app/dash/sidebar-include.html" %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-12">
          <div class="row">

            <!-- Recent Sales -->
            <div class="col-12">
              <div class="card recent-sales overflow-auto">


                <div class="card-body">
                  <h5 class="card-title">My Orders <span></span></h5>
                  <table class="table table-borderless datatable">
                    <thead>
                      <tr>
                        <th scope="col">#ID</th>
                        <th scope="col">Customer</th>
                        <th scope="col">Reference Code</th>
                        <th scope="col">Price</th>
                        <th scope="col">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for order in orders %}
                      <tr>
                        <th scope="row"><a href="#">#{{order.id}}</a></th>
                        <td>{{order.user.username}}</td>
                        <td><a href="#" class="text-primary">{{order.ref_code}}</a></td>
                        <td>${{order.get_total}}</td>
                        {% if order.get_status_display == "On delivery" %}
                        <td><span class="badge bg-info">On delivery</span></td>
                        {% elif order.get_status_display == "Delivered" %}
                        <td><span class="badge bg-success">Delivered</span></td>
                        {% elif order.get_status_display == "Cancelled" %}
                        <td><span class="badge bg-danger">Cancelled</span></td>
                        {% elif order.get_status_display == "Refund requested" %}
                        <td><span class="badge bg-warning">Refund requested</span></td>
                        {% elif order.get_status_display == "Refund granted" %}
                        <td><span class="badge bg-success">Refund granted</span></td>
                        {% else %}
                        <td><span class="badge bg-warning">Processing</span></td>
                        {% endif %}                     
                      </tr>
                      {% endfor %}
                
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Recent Sales -->

          </div>
        </div><!-- End Left side columns -->


      </div>
    </section>

  </main><!-- End #main -->

  {% include 'app/dash/dash-bottom-include.html' %}
  {% endblock %}

app/templates/app/dash/dash-bottom-include.html
{% load static %}
  
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

app/templates/app/dash/dash.html
{% extends 'app/base.html' %}
{% load static %}
{% load cart_template_tags %}

{% block content %}
{% include 'app/dash/dash-head-include.html' %}
  <!-- ======= Header ======= -->
  <!--  -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'dashboard' %}" class="logo d-flex align-items-center">

        <span class="d-none d-lg-block">Aurora</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->


        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <!-- <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle"> -->
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.user.username}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'password_reset' %}">
                <i class="bi bi-person"></i>
                <span>Change password</span>
              </a>
            </li>
            <li>
              <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
              <i class="bi bi-box-arrow-left"></i>
              <span>Sign out</span>
            </a>
          </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header>
  <!-- End Header -->

{% include "app/dash/sidebar-include.html" %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-12">
          <div class="row">
            <!-- Recent Sales -->
            <div class="col-12">
              <div class="card recent-sales overflow-auto">

                <div class="card-body">
                  <h5 class="card-title">My orders <span>({{ recent_orders | length }})</span></h5>

                  <table class="table table-borderless datatable">
                    <thead>
                      <tr>
                        <th scope="col">#ID</th>
                        <th scope="col">Customer</th>
                        <th scope="col">Reference Code</th>
                        <th scope="col">Price</th>
                        <th scope="col">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for order in recent_orders %}
                      <tr>
                        <th scope="row"><a href="#">#{{order.id}}</a></th>
                        <td>{{order.user.username}}</td>
                        <td><a href="{% url 'order-detail' order.id %}" class="text-primary">{{order.ref_code}}</a></td>
                        <td>${{order.get_total}}</td>
                        {% if order.get_status_display == "On delivery" %}
                        <td><span class="badge bg-info">On delivery</span></td>
                        {% elif order.get_status_display == "Delivered" %}
                        <td><span class="badge bg-success">Delivered</span></td>
                        {% elif order.get_status_display == "Cancelled" %}
                        <td><span class="badge bg-danger">Cancelled</span></td>
                        {% elif order.get_status_display == "Refund requested" %}
                        <td><span class="badge bg-warning">Refund requested</span></td>
                        {% elif order.get_status_display == "Refund granted" %}
                        <td><span class="badge bg-success">Refund granted</span></td>
                        {% else %}
                        <td><span class="badge bg-warning">Processing</span></td>
                        {% endif %}                     
                      </tr>
                      {% endfor %}
                
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Recent Sales -->

            <!-- Top Selling -->
            <div class="col-12">
              <div class="card top-selling overflow-auto">

                <div class="card-body pb-0">
                  <h5 class="card-title">Top Selling <span>| Today</span></h5>

                  <table class="table table-borderless">
                    <thead>
                      <tr>
                        <th scope="col">Preview</th>
                        <th scope="col">Product</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for item in most_popular_items %}
                      <tr>
                        <th scope="row"><a href="#"><img src="{{item.image}}" alt="No Image"></a></th>
                        <td><a href="{% url 'item-detail' item.id %}" class="text-primary fw-bold">{{item.name}}</a></td>
                        <td>${{item.price}}</td>
                        <td class="fw-bold">{{item.quantity_sold}}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Top Selling -->

          </div>
        </div><!-- End Left side columns -->


      </div>
    </section>

  </main><!-- End #main -->

  {% include 'app/dash/dash-bottom-include.html' %}
  {% endblock %}


app/templates/app/dash/order-detail.html
{% extends 'app/base.html' %}
{% load static %}
{% load cart_template_tags %}

{% block content %}
{% include 'app/dash/dash-head-include.html' %}
  <!-- ======= Header ======= -->
  <!--  -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'dashboard' %}" class="logo d-flex align-items-center">

        <span class="d-none d-lg-block">Aurora</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->


        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <!-- <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle"> -->
            <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.username}}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{request.user.username}}</h6>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'password_reset' %}">
                <i class="bi bi-person"></i>
                <span>Change password</span>
              </a>
            </li>
            <li>
                <a class="dropdown-item d-flex align-items-center" href="{% url 'logout' %}">
                <i class="bi bi-box-arrow-left"></i>
                <span>Sign out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header>
  <!-- End Header -->

{% include "app/dash/sidebar-include.html" %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-12">
          <div class="row">

            <!-- Order details -->
            <div class="col-12">
              <div class="card top-selling overflow-auto">

                <div class="card-body pb-0">
                  <h5 class="card-title">My order #{{order.id}}</span></h5>

                  <table class="table table-borderless">
                    <thead>
                      <tr>
                        <th scope="col">Total</th>
                        <th scope="col">Date Ordered</th>
                        <th scope="col">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>${{order.get_total}}</td>
                        <td>{{order.ordered_date}}</td>
                        {% if order.get_status_display == "On delivery" %}
                        <td><span class="badge bg-info">On delivery</span></td>
                        {% elif order.get_status_display == "Delivered" %}
                        <td><span class="badge bg-success">Delivered</span></td>
                        {% elif order.get_status_display == "Cancelled" %}
                        <td><span class="badge bg-danger">Cancelled</span></td>
                        {% elif order.get_status_display == "Refund requested" %}
                        <td><span class="badge bg-warning">Refund requested</span></td>
                        {% elif order.get_status_display == "Refund granted" %}
                        <td><span class="badge bg-success">Refund granted</span></td>
                        {% else %}
                        <td><span class="badge bg-warning">Processing</span></td>
                        {% endif %}  
                      </tr>
                    </tbody>
                  </table>

                </div>

              </div>
            </div><!-- End Order details -->

            <!-- Order details -->
            <div class="col-12">
                <div class="card top-selling overflow-auto">
  
                  <div class="card-body pb-0">
                    <h5 class="card-title">Order Items</span></h5>
  
                    <table class="table table-borderless">
                      <thead>
                        <tr>
                          <th scope="col">Preview</th>
                          <th scope="col">Product</th>
                          <th scope="col">Price</th>
                          <th scope="col">Quantity</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for item in order.items.all %}
                        <tr>
                          <th scope="row"><img src="{{ item.item.itemimage_set.first.imageURL }}" alt="No Image"></th>
                          <td>{{item.item.name}}</td>
                          {% if item.item.discount_price %}
                          <td class="cart__price">$ {{item.get_total_discount_item_price}}
                          <span class="bootstrap badge badge-success">Saved ${{ item.get_amount_saved }}</span>
                          </td>
                          {% else %}
                          <td class="cart__price">${{item.get_total_item_price}}</td>
                          {% endif %}
                          <td>x{{item.quantity}}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
  
                  </div>
  
                </div>
              </div><!-- End Order details -->



            <!-- Delivery address -->
            <div class="col-12">
                <div class="card top-selling overflow-auto">
  
                  <div class="card-body pb-0">
                    <h5 class="card-title">Delivery Info</span></h5>
  
                    <table class="table table-borderless">
                      <thead>
                        <tr>
                          <th scope="col">Full Name</th>
                          <th scope="col">Phone</th>
                          <th scope="col">House Address</th>
                          <th scope="col">City</th>
                          <th scope="col">Postal Code</th>
                          <th scope="col">Counry</th>
                          <th scope="col">Order Notes</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>{{order.full_name}}</td>
                          <td>{{order.phone}}</td>
                          <td>{{order.house_address}}</td>
                          <td>{{order.city}}</td>
                          <td>{{order.postal_code}}</td>
                          <td>{{order.country}}</td>
                          <td>{{order.order_notes}}</td>
                        </tr>
                      </tbody>
                    </table>
  
                  </div>
  
                </div>
              </div><!-- End Delivery address -->

          </div>
        </div><!-- End Left side columns -->


      </div>
    </section>

  </main><!-- End #main -->

  {% include 'app/dash/dash-bottom-include.html' %}
  {% endblock %}

app/templates/app/dash/sidebar-include.html
  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href="{% url 'dashboard' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->
    </ul>

  </aside><!-- End Sidebar-->